#ifndef DATASET_INC
#define DATASET_INC

#include <string>
#include <sstream>
#include<algorithm>
#include "time.h"
#include "mainTensor.H"
#include "Vocab.H"
#include "DataSet.H"
#include "NgramDataSet.H"
#include "NgramRankDataSet.H"
#include "NgramNCEDataSet.H"
#include "NgramPhraseTranslationDataSet.H"
#include "NgramWordTranslationDataSet.H"
#include "NgramNCEWordTranslationDataSet.H"
#include "RecurrentDataSet.H"
#include "FunctionDataSet.H"

#endif
