#ifndef MODULE_INC
#define MODULE_INC
#include "mainTensor.H"
#include "Module.H" 
#include "Linear.H"
#include "Linear_Bayes.H"
#include "MaxLinear.H"
#include "BLinear.H"
#include "RLinear.H"
#include "RRLinear.H"
#include "LookupTable.H"
#include "LookupTable_Bayes.H"
#include "Tanh.H"
#include "Sigmoid.H"
#include "Sequential.H"
#include "Sequential_Bayes.H"
#include "LinearSoftmax.H"
#include "LinearSoftmax_Bayes.H"
#include "FunctionSequential.H"

#endif
